In [1]:

#statement to import numpy
import numpy as np

In [2]:
prime_num=np.array([2,3,5,7,11])
print(prime_num)

[ 2  3  5  7 11]


In [ ]:
#two dimensional array
another_num=np.array([[1,2],[3,4]])
print(another_num)

[[1 2]
 [3 4]]


In [ ]:
#three dimensional array
three_di=np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])
print(three_di)
print(three_di.shape)
print(three_di.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3


In [ ]:
four_di=np.array([[[[1,2],[3,4]],[[4,6],[5,6]]],
                [[[1,3],[3,5]],[[2,6],[8,9]]]])#,ndmin=5)
print(four_di)
#print(four_di.T)
print(four_di.shape)
print(four_di.ndim)

[[[[1 2]
   [3 4]]

  [[4 6]
   [5 6]]]


 [[[1 3]
   [3 5]]

  [[2 6]
   [8 9]]]]
(2, 2, 2, 2)
4


### ndarray inspection

In [ ]:
#shape
alma_num=np.array([[1,2,3],[3,4,5]])
print(alma_num.shape)


(2, 3)
2


In [ ]:
arr=np.array([[[1,2,2],[2,3,5]],
             [[1,5,8],[9,5,6]],
             [[7,5,9],[4,5,6]],
             [[7,8,9],[5,3,6]],
            [[3,9,5],[8,6,5]]])
print(arr.shape)

(5, 2, 3)


In [ ]:
#ndim
arr1=np.array([[[1,2,2],[2,3,5]],
             [[1,5,8],[9,5,6]],
             [[7,5,9],[4,5,6]],
             [[7,8,9],[5,3,6]],
            [[3,9,5],[8,6,5]]])
print(f"the array dimension is: {arr1.ndim}")

the array dimension is: 3


In [ ]:
#size
arr2=np.array([[[1,2,2],[2,3,5]],
             [[1,5,8],[9,5,6]],
             [[7,5,9],[4,5,6]],
             [[7,8,9],[5,3,6]],
            [[3,9,5],[8,6,5]]])
print("the no.of elements are:",arr2.size)


the no.of elements are: 30


In [ ]:
#dtype
arr3=np.array([[[1,2,2],[2,3,5]],
             [[1,5,8],[9,5,6]],
             [[7,5,9],[4,5,6]],
             [[7,8,9],[5,3,6]],
            [[3,9,5],[8,6,5]]])
print(arr3.dtype)

int64


In [ ]:
#astype
#before changing type
arr4=np.array([1,2,6])
print(arr4.dtype)
#after changing type
arr5=arr4.astype('float64')
print(arr5.dtype)

int64
float64


In [ ]:
#intialize zeros to array
zero_array=np.zeros((3,3))#default dtype is float
another_zero_array=np.zeros((2,3),dtype=int)
print(zero_array)
print(another_zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]


In [ ]:
#intialize with ones
ones_array=np.ones((3,3))
another_ones_array=np.ones((2,3),dtype=int)
print(ones_array)
print(another_ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]


## arange function

In [ ]:
range_arr=np.arange(5)
print(range_arr)

[0 1 2 3 4]


In [ ]:
another_range=np.arange(0,100,10)
print(another_range)

[ 0 10 20 30 40 50 60 70 80 90]


In [ ]:
arr8=np.linspace(0,20,10,endpoint=True,retstep=True,dtype=int)
print(arr8)

(array([ 0,  2,  4,  6,  8, 11, 13, 15, 17, 20]), 2.2222222222222223)


In [ ]:
#getting an random array
random_array=np.random.random((2,3))#defualt we get float
print(random_array)

[[0.37356438 0.29887431 0.41421263]
 [0.28392079 0.36174332 0.88336048]]


In [ ]:
#getting random intger matrix
random_int_array=np.random.randint(0,10,size=(3,3))
print(random_int_array)
print(random_int_array.T)#transpose of a matrix

[[3 1 1]
 [1 7 2]
 [7 0 6]]
[[3 1 7]
 [1 7 0]
 [1 2 6]]


In [ ]:
#converting the list and tuple in ndarray
tuple_array=(1,2,3,5)
list_array=[1,5,6,3]
ndarray_tuple=np.asarray(tuple_array)
ndarray_list=np.asarray(list_array)
print(ndarray_tuple,"\n")
print(ndarray_list)

[1 2 3 5] 

[1 5 6 3]


In [ ]:
s=np.arange(0,10)
s=s[2:8]
print(s)

[2 3 4 5 6 7]


In [ ]:
#slicing in two D array
k=np.array([[1,2,3],[4,5,6]])
k=k[1,2]
print(k)

6


In [ ]:
d=np.array([[1,2,3],[5,5,6],[7,8,9]])
print(d,"\n")
print(d[0:2],"\n")
#getting a row
print(d[0:2,-2:],"\n")
#getting colum
print(d[:,0:1])

[[1 2 3]
 [5 5 6]
 [7 8 9]] 

[[1 2 3]
 [5 5 6]] 

[[2 3]
 [5 6]] 

[[1]
 [5]
 [7]]


### Array Manipulition

In [ ]:
#transpose of array
k=np.random.randint(0,5,size=(2,3))
print(k,"\n")
print(k.T)

[[2 1 2]
 [4 2 4]] 

[[2 4]
 [1 2]
 [2 4]]


In [ ]:
#reshape of array
z=np.random.randint(0,6,size=(2,3))
print(z,"\n")
print(z.reshape(3,2))

[[3 1 3]
 [0 1 5]] 

[[3 1]
 [3 0]
 [1 5]]


In [ ]:
#resize of the array
n=np.random.randint(0,6,size=(2,4,6))
print(n,"\n")
print(n.shape,"\n")
new_shape=(2,3,5)
print(np.resize(n,new_shape))

[[[1 0 0 1 5 2]
  [3 0 1 3 0 4]
  [5 3 0 1 3 5]
  [1 4 2 0 4 1]]

 [[2 5 1 1 1 1]
  [2 5 5 0 1 4]
  [4 3 2 2 1 0]
  [2 3 4 2 5 2]]] 

(2, 4, 6) 

[[[1 0 0 1 5]
  [2 3 0 1 3]
  [0 4 5 3 0]]

 [[1 3 5 1 4]
  [2 0 4 1 2]
  [5 1 1 1 1]]]


In [ ]:
#flatten the array
f=np.random.randint(0,9,size=(3,4,6))
print(f,"\n")
print(f.flatten())

[[[3 4 0 3 8 4]
  [5 5 7 6 5 6]
  [6 4 1 7 5 7]
  [0 6 5 4 1 0]]

 [[8 1 3 0 2 1]
  [2 1 1 8 2 3]
  [0 8 0 2 6 1]
  [6 6 8 0 2 4]]

 [[1 3 0 2 8 8]
  [1 5 8 2 8 5]
  [8 6 5 1 4 3]
  [5 3 2 2 6 7]]] 

[3 4 0 3 8 4 5 5 7 6 5 6 6 4 1 7 5 7 0 6 5 4 1 0 8 1 3 0 2 1 2 1 1 8 2 3 0
 8 0 2 6 1 6 6 8 0 2 4 1 3 0 2 8 8 1 5 8 2 8 5 8 6 5 1 4 3 5 3 2 2 6 7]


In [ ]:
#copy in list
a=[1,2,3]
b=a.copy()
b[0]=5
print(a)
print(b)

[1, 2, 3]
[5, 2, 3]


In [ ]:
#better to use copy method on both list and array
q=np.array([4,5,6])
a=q.copy()
a[1]=9
print(q)
print(a)

[4 5 6]
[4 9 6]


In [ ]:
#x=np.random.randint(0,10,size=(10,10))
x=np.ones((10,10),dtype=int)
for i in range(len(x)):
  for j in range(len(x[i])):
    if i==j:
      x[i,j]=0
print(x)



[[0 1 1 1 1 1 1 1 1 1]
 [1 0 1 1 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1]
 [1 1 1 1 1 0 1 1 1 1]
 [1 1 1 1 1 1 0 1 1 1]
 [1 1 1 1 1 1 1 0 1 1]
 [1 1 1 1 1 1 1 1 0 1]
 [1 1 1 1 1 1 1 1 1 0]]


In [ ]:
rows=np.linspace(1,50,10)
lists=[]
for i in rows:
  lists.append(np.linspace(i,i*100,10,endpoint=True,dtype=int))
print(rows,"\n")
print(np.array(lists))

[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ] 

[[   1   12   23   34   45   56   67   78   89  100]
 [   6   77  148  219  290  360  431  502  573  644]
 [  11  142  273  404  535  665  796  927 1058 1188]
 [  17  208  398  589  780  970 1161 1352 1542 1733]
 [  22  273  523  774 1025 1275 1526 1776 2027 2277]
 [  28  338  649  959 1270 1580 1890 2201 2511 2822]
 [  33  404  774 1144 1515 1885 2255 2626 2996 3366]
 [  39  469  899 1329 1760 2190 2620 3050 3480 3911]
 [  44  534 1024 1514 2005 2495 2985 3475 3965 4455]
 [  50  600 1150 1700 2250 2800 3350 3900 4450 5000]]


In [ ]:
k=np.linspace(1,100,10,dtype=int)
k

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [ ]:
l=[i*i for i in range(0,101) ]
a=np.array(l)
#m=(10,10)
print(np.resize(a,(10,10)))

[[   0    1    4    9   16   25   36   49   64   81]
 [ 100  121  144  169  196  225  256  289  324  361]
 [ 400  441  484  529  576  625  676  729  784  841]
 [ 900  961 1024 1089 1156 1225 1296 1369 1444 1521]
 [1600 1681 1764 1849 1936 2025 2116 2209 2304 2401]
 [2500 2601 2704 2809 2916 3025 3136 3249 3364 3481]
 [3600 3721 3844 3969 4096 4225 4356 4489 4624 4761]
 [4900 5041 5184 5329 5476 5625 5776 5929 6084 6241]
 [6400 6561 6724 6889 7056 7225 7396 7569 7744 7921]
 [8100 8281 8464 8649 8836 9025 9216 9409 9604 9801]]


In [ ]:
#insert method
t=np.random.randint(10,20,(2,3,4))
print(t,"\n")
print(np.insert(t,0,56,axis=0))
#for two layers axis 0 add new array

[[[13 18 10 17]
  [11 18 12 12]
  [13 16 12 19]]

 [[10 14 16 19]
  [19 10 19 19]
  [16 16 11 19]]] 

[[[56 56 56 56]
  [56 56 56 56]
  [56 56 56 56]]

 [[13 18 10 17]
  [11 18 12 12]
  [13 16 12 19]]

 [[10 14 16 19]
  [19 10 19 19]
  [16 16 11 19]]]


In [ ]:
#insert axis=1
np.insert(t,1,21,axis=1)
#axis 1 add new row

array([[[18, 10, 19, 16],
        [21, 21, 21, 21],
        [10, 14, 17, 11],
        [19, 12, 14, 10]],

       [[14, 18, 10, 12],
        [21, 21, 21, 21],
        [13, 12, 14, 18],
        [16, 11, 15, 17]]])

In [ ]:
#insert axis=2
np.insert(t,2,36,axis=2)
#axis 2 add new col

array([[[18, 10, 36, 19, 16],
        [10, 14, 36, 17, 11],
        [19, 12, 36, 14, 10]],

       [[14, 18, 36, 10, 12],
        [13, 12, 36, 14, 18],
        [16, 11, 36, 15, 17]]])

In [ ]:
v=np.random.randint(0,20,size=(3,3))
print(v,"\n")
print(np.insert(v,1,65,axis=0),"\n")#horizontal
print(np.insert(v,1,65,axis=1))#vertical

[[17 13  3]
 [11 17  1]
 [ 9  1  1]] 

[[17 13  3]
 [65 65 65]
 [11 17  1]
 [ 9  1  1]] 

[[17 65 13  3]
 [11 65 17  1]
 [ 9 65  1  1]]


In [ ]:
#append method
h=np.array([[1,2,3],[4,5,6]])
print(h)
print(np.append(h,[[7,8,9]],axis=0))


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#appending two arrays
b=np.random.randint(2,9,size=(2,3,3))
print(b,"\n")


[[[3 5 8]
  [2 8 4]
  [7 2 5]]

 [[7 8 2]
  [4 6 8]
  [7 7 6]]] 



In [ ]:
a=np.random.randint(3,10,size=(2,3,3))
print(a)

[[[5 9 3]
  [4 7 4]
  [9 9 9]]

 [[7 3 7]
  [8 5 8]
  [5 5 9]]]


In [ ]:
np.append(a,b,axis=1)#vertically appending

array([[[5, 9, 3],
        [4, 7, 4],
        [9, 9, 9],
        [3, 5, 8],
        [2, 8, 4],
        [7, 2, 5]],

       [[7, 3, 7],
        [8, 5, 8],
        [5, 5, 9],
        [7, 8, 2],
        [4, 6, 8],
        [7, 7, 6]]])

In [ ]:
#delete method
d=np.random.randint(2,4,size=(3,3))
print(d)

[[2 3 2]
 [3 2 3]
 [3 2 3]]


In [ ]:
print(np.delete(d,1,axis=1),"\n")
print(np.delete(d,(0,1),axis=1))

[[2 2]
 [3 3]
 [3 3]] 

[[2]
 [3]
 [3]]


In [ ]:
#unique method
u=np.random.randint(2,10,size=(2,3,3))
print(u,"\n")
print(np.unique(u,return_index=True,return_counts=True))#return tuple

[[[4 4 8]
  [4 3 5]
  [9 2 7]]

 [[4 4 4]
  [2 4 5]
  [7 7 4]]] 

(array([2, 3, 4, 5, 7, 8, 9]), array([7, 4, 0, 5, 8, 2, 6]), array([2, 1, 8, 2, 3, 1, 1]))


## The Concept of Broadcasting

In [ ]:
np.arange(3)+5

array([5, 6, 7])

In [ ]:
np.arange(3)+np.ones((3,3))#default float

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
np.arange(3)+np.ones((3,3),dtype=int)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
print(np.arange(3).reshape(3,1),"\n")
print(np.arange(3),"\n")
print(np.arange(3).reshape(3,1)+np.arange(3))

[[0]
 [1]
 [2]] 

[0 1 2] 

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
a=np.random.randint(2,9,size=(2,3))
b=np.random.randint(0,12,size=(2,3))
print(a,"\n")
print(b,"\n")
print(np.add(a,b),"\n")
print(np.multiply(a,b),"\n")

[[8 2 2]
 [7 8 4]] 

[[ 7  2  1]
 [ 0 10 11]] 

[[15  4  3]
 [ 7 18 15]] 

[[56  4  2]
 [ 0 80 44]] 



In [ ]:
z=np.array([[4,5,6,7],[1,2,6,7]]).reshape(2,2,2)
print(z,"\n")
print(np.sum(z,axis=0),"\n")
print(np.sum(z,axis=1))

[[[4 5]
  [6 7]]

 [[1 2]
  [6 7]]] 

[[ 5  7]
 [12 14]] 

[[10 12]
 [ 7  9]]


In [ ]:
o=np.random.randint(2,6,size=(2,2,3))
print(o,'\n')
print(np.sum(o,axis=2))

[[[5 2 5]
  [4 4 3]]

 [[3 4 3]
  [3 2 2]]] 

[[12 11]
 [10  7]]


In [ ]:
#problem 1
#sum of first 5 rows  of thrid and fourth columns
p=np.random.randint(1,high=500000,size=(20,5))
print(p,"\n")
print(f"the sum is {np.sum(p[0:5,2:4])}")
print(np.size(p))

[[  1607 152314 398283 402442 288155]
 [111213  15636 119129 433683 129418]
 [334583 231780 437860 366058 132835]
 [374343  75532 375274  86462 101332]
 [213767  55831 387279 354619 196665]
 [  3072 436406 249850  33861 232503]
 [244928 391308 172807  60685  75811]
 [313707 187563 337269  30327 304811]
 [182527 233922 315631  66763  58307]
 [ 45641 125092 369215 236498 209990]
 [274080    592 156885 410368 137901]
 [159474  21973 146760 375743 254430]
 [146274 212295 289177 197842 393242]
 [470935 247149  75820 277306 454684]
 [100919 124490  86348 446076 376941]
 [123568 280404 258703 104543 236780]
 [259487 120232 234646 360609 491352]
 [145426 254709 249190 371297 414497]
 [244511 199007  16401    268 125675]
 [391511 319540 485019 295861 224981]] 

the sum is 3361089
100


In [ ]:
round(269**0.5,2)

16.4

In [ ]:
c=np.array([[19, 19],[ 6, 19],[ 6,  9],[11, 15],[13, 18],[10,  5],[ 8, 10],[12,  5],[13, 10],[ 8, 19]])
print(c)

[[19 19]
 [ 6 19]
 [ 6  9]
 [11 15]
 [13 18]
 [10  5]
 [ 8 10]
 [12  5]
 [13 10]
 [ 8 19]]


In [ ]:
e=np.full((10,10),10)
for i in range(c.size//2):
  for j in range(c.size//2):
    x = (c[i][0]-c[j][0])**2+(c[i][1]-c[j][1])**2
    e[i][j]=round(x**0.5,2)
print(e)


[[ 0 13 16  8  6 16 14 15 10 11]
 [13  0 10  6  7 14  9 15 11  2]
 [16 10  0  7 11  5  2  7  7 10]
 [ 8  6  7  0  3 10  5 10  5  5]
 [ 6  7 11  3  0 13  9 13  8  5]
 [16 14  5 10 13  0  5  2  5 14]
 [14  9  2  5  9  5  0  6  5  9]
 [15 15  7 10 13  2  6  0  5 14]
 [10 11  7  5  8  5  5  5  0 10]
 [11  2 10  5  5 14  9 14 10  0]]


### **Pandas**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pd.__version__

np.__version__

'1.22.4'

In [ ]:
num=pd.Series([1,2,3,4,5])
print(num)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
se=pd.Series([2,5,8,6,7],index=[12,13,14,15,16],name="no of apples")
se

12    2
13    5
14    8
15    6
16    7
Name: no of apples, dtype: int64

### DataFrame

In [ ]:
random_num=np.random.randint(2,6,size=(3,3))
data_frame=pd.DataFrame(random_num,columns=['ABC','XYZ','PQT'],index=['First','Second','Thrid'])
data_frame

ABC  XYZ  PQT
First     3    4    3
Second    5    4    3
Thrid     4    2    5

In [ ]:
list_of_list=[['Amar',24],['Akbar',23],['Anthony',25]]
another_data=pd.DataFrame(list_of_list,columns=['Name','Age'],index=[1,2,3])
another_data

Name  Age
1     Amar   24
2    Akbar   23
3  Anthony   25

## using dictionary

In [ ]:
emp_dict={'Employe Name':['Rancho','raju','farhan'],'Income':['1000000','75000','25000']}
i=pd.DataFrame(emp_dict,index=[1,2,3])
i

Employe Name   Income
1       Rancho  1000000
2         raju    75000
3       farhan    25000

In [ ]:
series_dict={'Firts series':pd.Series([2,6,8,9]),
             'second series':pd.Series([5,4,6,3])}
p=pd.DataFrame(series_dict)
p

Firts series  second series
0             2              5
1             6              4
2             8              6
3             9              3

In [ ]:
list_dic={'a':1,'b':2,'c':3},{'a':10,'b':20,'c':30}
pd.DataFrame(list_dic)

a   b   c
0   1   2   3
1  10  20  30

In [ ]:
student_dict={'ID':['22075A6701','22075A6702','22075A6703','22075A6704'],'Name':['Abhisek','Manoj','Riyaz','Affan']}
m=pd.DataFrame(student_dict,index=[1,2,3,4])
m

ID     Name
1  22075A6701  Abhisek
2  22075A6702    Manoj
3  22075A6703    Riyaz
4  22075A6704    Affan

In [ ]:
ar=np.random.randint(2,100,(100,5))
b=pd.DataFrame(ar,columns=['A','B','C','D','E'])
b

A   B   C   D   E
0    4  21  22  66  83
1    9  31  87  21  85
2   99  66  85  54  33
3    2  28  21   3  90
4   43  80   5  99  92
..  ..  ..  ..  ..  ..
95  14  18  57  98   9
96  45  80  13   5  52
97  58  25   6   2   5
98  30  22  79  32   5
99  42  55   3  27  32

[100 rows x 5 columns]

## **head()**
prints the first n rows of the dataframe.By default it prints the first 5 rows

In [ ]:
b.head()

A   B   C   D   E
0   4  21  22  66  83
1   9  31  87  21  85
2  99  66  85  54  33
3   2  28  21   3  90
4  43  80   5  99  92

In [ ]:
b.head(10)

A   B   C   D   E
0   4  21  22  66  83
1   9  31  87  21  85
2  99  66  85  54  33
3   2  28  21   3  90
4  43  80   5  99  92
5  30   3  50  53  49
6  75  24  61  99  39
7  78  97  73  82   7
8  39  48  79  53  10
9   8  96  83  27  85

### **tail()**
Prints the last n rows of the dataframe.By default it prints the last 5 rows

In [ ]:
b.tail()

A   B   C   D   E
95  14  18  57  98   9
96  45  80  13   5  52
97  58  25   6   2   5
98  30  22  79  32   5
99  42  55   3  27  32

In [ ]:
b.tail(10)

A   B   C   D   E
90  59  30  50  60  31
91  25  56  18  79  74
92  96  89  69  43  85
93  40  43  12  81  74
94  45  20  68  47  60
95  14  18  57  98   9
96  45  80  13   5  52
97  58  25   6   2   5
98  30  22  79  32   5
99  42  55   3  27  32

### **columns**
prints the list odf columns in a dataframe


In [ ]:
list(b.columns)

['A', 'B', 'C', 'D', 'E']

### info()
prints the basic information about our dataframe

In [ ]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       100 non-null    int64
 1   B       100 non-null    int64
 2   C       100 non-null    int64
 3   D       100 non-null    int64
 4   E       100 non-null    int64
dtypes: int64(5)
memory usage: 4.0 KB


## rename()
Rename the columns of the dataframe



In [ ]:
m

ID     Name
1  22075A6701  Abhisek
2  22075A6702    Manoj
3  22075A6703    Riyaz
4  22075A6704    Affan

In [ ]:
v=m.rename(columns={'ID':'Student ID','Name':'Students Names'})
v

student ID students names
1  22075A6701        Abhisek
2  22075A6702          Manoj
3  22075A6703          Riyaz
4  22075A6704          Affan

## Loading a CSV(Common-separated Values)file

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
path="/content/drive/MyDrive/Datasets/best-selling-books.csv"

In [ ]:
#store in a variable to use head()
df=pd.read_csv(path)
df.head()
#df.info()

Book                 Author(s)  \
0                      A Tale of Two Cities           Charles Dickens   
1       The Little Prince (Le Petit Prince)  Antoine de Saint-Exupéry   
2  Harry Potter and the Philosopher's Stone             J. K. Rowling   
3                  And Then There Were None           Agatha Christie   
4            Dream of the Red Chamber (紅樓夢)                Cao Xueqin   

  Original language  First published  Approximate sales in millions  \
0           English             1859                          200.0   
1            French             1943                          200.0   
2           English             1997                          120.0   
3           English             1939                          100.0   
4           Chinese             1791                          100.0   

                Genre  
0  Historical fiction  
1             Novella  
2             Fantasy  
3             Mystery  
4         Family saga

In [ ]:
#does not ()
df.shape


(174, 6)

### **describe**()
This method gives the overall descriptive summary of the dataframe.This works
only on numerical columns

In [ ]:
df.describe()

First published  Approximate sales in millions
count       174.000000                     174.000000
mean       1962.522989                      30.097126
std          64.268737                      27.957985
min        1304.000000                      10.000000
25%        1947.000000                      14.000000
50%        1974.000000                      20.000000
75%        1995.000000                      36.300000
max        2018.000000                     200.000000

## **iloc**
This method gets the row and columns at a paticular index and iloc stands for index location

In [ ]:
#df.iloc[:15,:5]
df.iloc[:,:3]

Book  \
0                                 A Tale of Two Cities   
1                  The Little Prince (Le Petit Prince)   
2             Harry Potter and the Philosopher's Stone   
3                             And Then There Were None   
4                       Dream of the Red Chamber (紅樓夢)   
..                                                 ...   
169                                           The Goal   
170                                     Fahrenheit 451   
171                                     Angela's Ashes   
172  The Story of My Experiments with Truth (સત્યના...   
173                              Bridget Jones's Diary   

                      Author(s) Original language  
0               Charles Dickens           English  
1      Antoine de Saint-Exupéry            French  
2                 J. K. Rowling           English  
3               Agatha Christie           English  
4                    Cao Xueqin           Chinese  
..                          ...               ...  
169         Eliyahu M. Goldratt           English  
170                Ray Bradbury           English  
171               Frank McCourt           English  
172  Mohandas Karamchand Gandhi          Gujarati  
173              Helen Fielding           English  

[174 rows x 3 columns]

## **loc**
gets rows or columns with particular lables from the index

In [ ]:
df.loc[20:30,['Book','Author(s)']]

Book               Author(s)
20                             You Can Heal Your Life              Louise Hay
21  One Hundred Years of Solitude (Cien años de so...  Gabriel García Márquez
22                                             Lolita        Vladimir Nabokov
23                                              Heidi           Johanna Spyri
24       The Common Sense Book of Baby and Child Care          Benjamin Spock
25                               Anne of Green Gables    Lucy Maud Montgomery
26                                       Black Beauty             Anna Sewell
27          The Name of the Rose (Il Nome della Rosa)             Umberto Eco
28                               The Eagle Has Landed            Jack Higgins
29                                     Watership Down           Richard Adams
30                                    The Hite Report              Shere Hite

In [ ]:
#df.loc[50:60,['Original language']]
df.loc[:,['Original language']]

Original language
0             English
1              French
2             English
3             English
4             Chinese
..                ...
169           English
170           English
171           English
172          Gujarati
173           English

[174 rows x 1 columns]

In [ ]:
#boolean indexing
e = df[df['Original language']!='English']
e.head()

Book  \
1                 The Little Prince (Le Petit Prince)   
4                      Dream of the Red Chamber (紅樓夢)   
8                 Vardi Wala Gunda (वर्दी वाला गुंडा)   
16                       The Alchemist (O Alquimista)   
21  One Hundred Years of Solitude (Cien años de so...   

                   Author(s) Original language  First published  \
1   Antoine de Saint-Exupéry            French             1943   
4                 Cao Xueqin           Chinese             1791   
8         Ved Prakash Sharma             Hindi             1992   
16              Paulo Coelho        Portuguese             1988   
21    Gabriel García Márquez           Spanish             1967   

    Approximate sales in millions          Genre  
1                           200.0        Novella  
4                           100.0    Family saga  
8                            80.0      Detective  
16                           65.0        Fantasy  
21                           50.0  Magic realism

In [ ]:
y=df[(df['First published']>1900)  & (df['Original language']!='En')]
y.head()

Book                 Author(s)  \
1       The Little Prince (Le Petit Prince)  Antoine de Saint-Exupéry   
2  Harry Potter and the Philosopher's Stone             J. K. Rowling   
3                  And Then There Were None           Agatha Christie   
5                                The Hobbit          J. R. R. Tolkien   
6      The Lion, the Witch and the Wardrobe               C. S. Lewis   

  Original language  First published  Approximate sales in millions  \
1            French             1943                          200.0   
2           English             1997                          120.0   
3           English             1939                          100.0   
5           English             1937                          100.0   
6           English             1950                           85.0   

                         Genre  
1                      Novella  
2                      Fantasy  
3                      Mystery  
5                      Fantasy  
6  Fantasy, Children's fiction

## **Manipulate columns**

In [ ]:
#adding new column
df["sales in trillon"]=df['Approximate sales in millions']*2
df.head()

Book                 Author(s)  \
0                      A Tale of Two Cities           Charles Dickens   
1       The Little Prince (Le Petit Prince)  Antoine de Saint-Exupéry   
2  Harry Potter and the Philosopher's Stone             J. K. Rowling   
3                  And Then There Were None           Agatha Christie   
4            Dream of the Red Chamber (紅樓夢)                Cao Xueqin   

  Original language  First published  Approximate sales in millions  \
0           English             1859                          200.0   
1            French             1943                          200.0   
2           English             1997                          120.0   
3           English             1939                          100.0   
4           Chinese             1791                          100.0   

                Genre  sales in trillon  
0  Historical fiction             400.0  
1             Novella             400.0  
2             Fantasy             240.0  
3             Mystery             200.0  
4         Family saga             200.0

## **Drop column**

In [ ]:
df.drop(['Approximate sales in millions'],axis=1)
df.drop([4],axis=0)

Author(s) Original language  First published  \
0               Charles Dickens           English             1859   
1      Antoine de Saint-Exupéry            French             1943   
2                 J. K. Rowling           English             1997   
3               Agatha Christie           English             1939   
5              J. R. R. Tolkien           English             1937   
..                          ...               ...              ...   
169         Eliyahu M. Goldratt           English             1984   
170                Ray Bradbury           English             1953   
171               Frank McCourt           English             1996   
172  Mohandas Karamchand Gandhi          Gujarati             1929   
173              Helen Fielding           English             1996   

     Approximate sales in millions               Genre  sales in trillon  
0                            200.0  Historical fiction             400.0  
1                            200.0             Novella             400.0  
2                            120.0             Fantasy             240.0  
3                            100.0             Mystery             200.0  
5                            100.0             Fantasy             200.0  
..                             ...                 ...               ...  
169                           10.0                 NaN              20.0  
170                           10.0                 NaN              20.0  
171                           10.0                 NaN              20.0  
172                           10.0                 NaN              20.0  
173                           10.0                 NaN              20.0  

[173 rows x 6 columns]

# **apply()method to apply a function to every row in pandas dataframe**

In [ ]:
df['Approximate sales in millions'].sum()

5236.9

In [ ]:
def upper_case(col):
  return col.upper()

In [ ]:
df['Cap_Author(s)']=df['Author(s)'].apply(upper_case)
df.head()

Author(s) Original language  First published  \
0           Charles Dickens           English             1859   
1  Antoine de Saint-Exupéry            French             1943   
2             J. K. Rowling           English             1997   
3           Agatha Christie           English             1939   
4                Cao Xueqin           Chinese             1791   

   Approximate sales in millions               Genre  sales in trillon  \
0                          200.0  Historical fiction             400.0   
1                          200.0             Novella             400.0   
2                          120.0             Fantasy             240.0   
3                          100.0             Mystery             200.0   
4                          100.0         Family saga             200.0   

              Cap_Author(s)  
0           CHARLES DICKENS  
1  ANTOINE DE SAINT-EXUPÉRY  
2             J. K. ROWLING  
3           AGATHA CHRISTIE  
4                CAO XUEQIN

In [ ]:
#sorting in ascending order
df.sort_values(['Approximate sales in millions','sales in trillon'], ascending=True)

Author(s) Original language  First published  \
146          Erskine Caldwell           English             1932   
147           Astrid Lindgren           Swedish             1981   
149             Andrew Morton           English             1992   
150          Kathryn Stockett           English             2009   
151             Joseph Heller           English             1961   
..                        ...               ...              ...   
4                  Cao Xueqin           Chinese             1791   
5            J. R. R. Tolkien           English             1937   
2               J. K. Rowling           English             1997   
0             Charles Dickens           English             1859   
1    Antoine de Saint-Exupéry            French             1943   

     Approximate sales in millions               Genre  sales in trillon  \
146                           10.0                 NaN              20.0   
147                           10.0                 NaN              20.0   
149                           10.0                 NaN              20.0   
150                           10.0                 NaN              20.0   
151                           10.0                 NaN              20.0   
..                             ...                 ...               ...   
4                            100.0         Family saga             200.0   
5                            100.0             Fantasy             200.0   
2                            120.0             Fantasy             240.0   
0                            200.0  Historical fiction             400.0   
1                            200.0             Novella             400.0   

                Cap_Author(s)  
146          ERSKINE CALDWELL  
147           ASTRID LINDGREN  
149             ANDREW MORTON  
150          KATHRYN STOCKETT  
151             JOSEPH HELLER  
..                        ...  
4                  CAO XUEQIN  
5            J. R. R. TOLKIEN  
2               J. K. ROWLING  
0             CHARLES DICKENS  
1    ANTOINE DE SAINT-EXUPÉRY  

[174 rows x 7 columns]

In [ ]:
#unique method
list(df['Original language'].unique())

['English',
 'French',
 'Chinese',
 'Hindi',
 'Portuguese',
 'Spanish',
 'German',
 'Italian',
 'Norwegian',
 'Russian',
 'Dutch',
 'Swedish',
 'Japanese',
 'Czech',
 'Yiddish',
 'Gujarati']

In [ ]:
df.Original_language.nunique()

AttributeError: ignored

## **Assignment problem**

In [ ]:
# List of urls
url_list = ['https://blog.hubspot.com/marketing/parts-url',
            'https://www.almabetter.com/enrollments',
            'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html',
            'https://www.programiz.com/python-programming/list']

In [ ]:
z=[i.split('/')[2]for i in url_list]
y=[i.split('/')[-1].split('.')[-1]for i in url_list]
y

['parts-url', 'enrollments', 'html', 'list']

In [ ]:
c=zip(z,y,url_list)
q=pd.DataFrame(c,columns=['url','Domain','main string'])
q



url       Domain  \
0    blog.hubspot.com    parts-url   
1  www.almabetter.com  enrollments   
2   pandas.pydata.org         html   
3   www.programiz.com         list   

                                         main string  
0       https://blog.hubspot.com/marketing/parts-url  
1             https://www.almabetter.com/enrollments  
2  https://pandas.pydata.org/pandas-docs/stable/r...  
3  https://www.programiz.com/python-programming/list